name: pet_welfrare_ph
description: "for pet services"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.4.1
  firebase_core: ^3.6.0
  fluttertoast: ^8.2.8
  qr_flutter: ^4.1.0
  convex_bottom_bar: ^3.2.0
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.8
  mailer: ^6.2.0
  shared_preferences: ^2.3.2
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  sn_progress_dialog: ^1.1.4
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  path: ^1.9.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  geolocator: ^13.0.1
  gal: ^2.3.1
  permission_handler: ^11.3.1
  video_player: ^2.1.10
  maplibre_gl: ^0.21.0
  chewie: ^1.10.0
  docx_to_text: ^1.0.1
  docx_template: ^0.4.0
  firebase_app_check: ^0.3.2+2
  firebase_admin: ^0.3.0
  cloud_functions: ^5.3.2
  http: ^0.13.3
  timeago: ^3.0.2
  philippines_rpcmb: ^0.0.3
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_fore.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/video/boy.mp4
    - assets/video/dogcat.mp4
    - assets/word/
    - assets/word/terms.txt

  fonts:
    - family: SmoochSans
      fonts:
        - asset: assets/fonts/SmoochSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SmoochSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/SmoochSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SmoochSans-Light.ttf
          weight: 300